### ISSUE TITLE
cannot use the object catched with handleFunction

### ISSUE THREAD

**Issue by shimozurdo** [BillelGuerfa/typeahead-angular2#1]
The directive actually works, but the handleFunction function is out of the this(angular scope) then I can not access to my declared variables on my Angular component class :(

**Comment by BillelGuerfa** [comment]
Hi @shimozurdo, when you declare your handleFunction at the class level, be sure to use the arrow notation : 
myFunction = (...)=>{...};
and not myFunction(){...} 
As the arrow notation will keep the 'this' keyword, and the original scope,
Hope this resolve your issue :)

**Comment by shimozurdo** [comment]
You are awesome!! thank you so much!
